//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OriginMenu.Adapters
{
    
    public class IModuleContractToViewAddInAdapter : OriginMenu.Views.IModule
    {
        private Start9.Api.Contracts.IModuleContract _contract;
        private System.AddIn.Pipeline.ContractHandle _handle;
        static IModuleContractToViewAddInAdapter()
        {
        }
        public IModuleContractToViewAddInAdapter(Start9.Api.Contracts.IModuleContract contract)
        {
            _contract = contract;
            _handle = new System.AddIn.Pipeline.ContractHandle(contract);
        }
        public OriginMenu.Views.IConfiguration Configuration
        {
            get
            {
                return OriginMenu.Adapters.IConfigurationAddInAdapter.ContractToViewAdapter(_contract.Configuration);
            }
            set
            {
                _contract.Configuration = OriginMenu.Adapters.IConfigurationAddInAdapter.ViewToContractAdapter(value);
            }
        }
        public OriginMenu.Views.IMessageContract MessageContract
        {
            get
            {
                return OriginMenu.Adapters.IMessageContractAddInAdapter.ContractToViewAdapter(_contract.MessageContract);
            }
        }
        public OriginMenu.Views.IReceiverContract ReceiverContract
        {
            get
            {
                return OriginMenu.Adapters.IReceiverContractAddInAdapter.ContractToViewAdapter(_contract.ReceiverContract);
            }
        }
        public void Initialize(OriginMenu.Views.IHost host)
        {
            _contract.Initialize(OriginMenu.Adapters.IHostAddInAdapter.ViewToContractAdapter(host));
        }
        internal Start9.Api.Contracts.IModuleContract GetSourceContract()
        {
            return _contract;
        }
    }
}

