//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OriginMenu.Adapters
{
    
    public class IReceiverContractViewToContractAddInAdapter : System.AddIn.Pipeline.ContractBase, Start9.Api.Contracts.IReceiverContractContract
    {
        private OriginMenu.Views.IReceiverContract _view;
        public IReceiverContractViewToContractAddInAdapter(OriginMenu.Views.IReceiverContract view)
        {
            _view = view;
        }
        public System.AddIn.Contract.IListContract<Start9.Api.Contracts.IReceiverEntryContract> Entries
        {
            get
            {
                return System.AddIn.Pipeline.CollectionAdapters.ToIListContract<OriginMenu.Views.IReceiverEntry, Start9.Api.Contracts.IReceiverEntryContract>(_view.Entries, OriginMenu.Adapters.IReceiverEntryAddInAdapter.ViewToContractAdapter, OriginMenu.Adapters.IReceiverEntryAddInAdapter.ContractToViewAdapter);
            }
        }
        internal OriginMenu.Views.IReceiverContract GetSourceView()
        {
            return _view;
        }
    }
}

